# https://hub.docker.com/_/node
# FROM node:16.17-alpine

# drop-in node replacement: https://docs.cypress.io/guides/getting-started/installing-cypress
FROM cypress/base:16

ARG PORT=3000
ARG CYPRESS_PORT=1234
ARG REACT_APP_BACKEND_URL

RUN apt-get update && \
	apt-get install -y \
	git \
	chromium

ENV PORT=$PORT
ENV CYPRESS_PORT=$CYPRESS_PORT
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
ENV NEXT_TELEMETRY_DISABLED 1

RUN npm install --global yarn

WORKDIR /opt/lib/
COPY . .
# COPY ./package.json ./yarn.lock ./
# RUN yarn

EXPOSE 3000
EXPOSE 1234
