# https://hub.docker.com/_/node
FROM node:16.17-alpine

ARG PORT=3000
ARG CYPRESS_PORT=1234
ARG BACKEND_URL

# Installs latest Chromium (89) package.
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn

ENV PORT=$PORT
ENV CYPRESS_PORT=$CYPRESS_PORT
ENV BACKEND_URL=$BACKEND_URL

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
ENV NEXT_TELEMETRY_DISABLED 1
RUN apk add --no-cache --update \
 bash sudo npm tree git
WORKDIR /opt/lib/
COPY . .
# COPY ./package.json ./yarn.lock ./
# RUN yarn

EXPOSE 3000
EXPOSE 1234
